#!/usr/bin/env php
<?php

// TODO: Remove all __DIR__ and use a define BASE_PATH in web and cli environments

require_once __DIR__ . '/src/Frame/Cli/Command/require.php';

use Frame\Cli\Command\CommandLoader;

$commandLoader = new CommandLoader();

$commandName = $argv[1] ?? null;
$arguments = array_slice($argv, 2);

if ($commandName) {
    $commandLoader->runCommand($commandName, $arguments);
} else {
    $commandLoader->help();
}